"""initial schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-12 14:15:37.012765
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_groups',
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('group_slug', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_slug')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_municipality', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CANDIDATE', 'EMPLOYER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['category_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('companies',
    sa.Column('tax_code', sa.String(length=14), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('international_name', sa.String(length=500), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('headquarters_address', sa.Text(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('company_size', sa.Enum('1-9', '10-24', '25-99', '100-499', '500-1000', '1000+', name='company_size'), nullable=False),
    sa.Column('category_group_id', sa.UUID(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='company_status'), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('verification_tier', sa.Enum('UNVERIFIED', 'VERIFIED', name='verification_tier'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_group_id'], ['category_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_index(op.f('ix_companies_tax_code'), 'companies', ['tax_code'], unique=True)
    op.create_table('cvs',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_cvs_candidate_id'), 'cvs', ['candidate_id'], unique=False)
    op.create_table('company_addresses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('address_detail', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('member_role', sa.Enum('OWNER', 'RECRUITER', name='member_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_company_members_user')
    )
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'FREELANCE', name='job_type'), nullable=False),
    sa.Column('experience_level', sa.Enum('NO_EXP', 'UNDER_1', '1_2', '2_3', '3_5', 'OVER_5', name='experience_level'), nullable=False),
    sa.Column('gender', sa.Enum('NOT_REQUIRED', 'MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('salary_type', sa.Enum('RANGE', 'FROM', 'UP_TO', 'AGREEMENT', name='salary_type'), nullable=False),
    sa.Column('salary_min', sa.BigInteger(), nullable=True),
    sa.Column('salary_max', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'EXPIRED', 'TAKEN_DOWN', name='job_status'), nullable=False),
    sa.Column('takedown_reason', sa.Text(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('requirements_html', sa.Text(), nullable=False),
    sa.Column('benefits_html', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_jobs_quantity_positive'),
    sa.CheckConstraint('salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min', name='ck_jobs_salary_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_category_id'), 'jobs', ['category_id'], unique=False)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_slug'), 'jobs', ['slug'], unique=True)
    op.create_index('ix_jobs_status_deadline', 'jobs', ['status', 'deadline'], unique=False)
    op.create_table('applications',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VIEWED', 'SHORTLISTED', 'REJECTED', 'HIRED', name='application_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cover_letter IS NULL OR length(cover_letter) <= 2000', name='ck_applications_cover_letter_length'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_applications_job_candidate')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_table('job_locations',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('address_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_locations_city_id'), 'job_locations', ['city_id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_saved_jobs_user_job')
    )
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_job_locations_city_id'), table_name='job_locations')
    op.drop_table('job_locations')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status_deadline', table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_category_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('company_members')
    op.drop_table('company_addresses')
    op.drop_index(op.f('ix_cvs_candidate_id'), table_name='cvs')
    op.drop_table('cvs')
    op.drop_index(op.f('ix_companies_tax_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cities')
    op.drop_table('category_groups')
    # ### end Alembic commands ###

    # Alembic không tự xoá PG enum type do create_table sinh ra. Không xoá thì
    # downgrade rồi upgrade lại sẽ lỗi "type ... already exists".
    for enum_name in (
        "application_status",
        "job_status",
        "salary_type",
        "gender",
        "experience_level",
        "job_type",
        "member_role",
        "verification_tier",
        "company_status",
        "company_size",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
